export { HowItWorksPage } from './HowItWorks/HowItWorksPage.jsx'
export { CRMPage } from './CRM/CRMPage.jsx'
export { DeliberationPage } from './Deliberation/DeliberationPage.jsx'
export { DueDiligencePage } from './DueDiligence/DueDiligencePage.jsx'
export { AdminPage } from './Admin/AdminPage.jsx'
