// Create Region nodes for major cities and Tbilisi districts
CREATE (r1:Region {name: 'Tbilisi', type: 'city', country: 'Georgia'})
CREATE (r2:Region {name: 'Tbilisi - Vake', type: 'district', parentCity: 'Tbilisi'})
CREATE (r3:Region {name: 'Tbilisi - Saburtalo', type: 'district', parentCity: 'Tbilisi'})
CREATE (r4:Region {name: 'Tbilisi - Dighomi', type: 'district', parentCity: 'Tbilisi'})
CREATE (r5:Region {name: 'Tbilisi - Mukhiani', type: 'district', parentCity: 'Tbilisi'})
CREATE (r6:Region {name: 'Tbilisi - Varketili', type: 'district', parentCity: 'Tbilisi'})
CREATE (r7:Region {name: 'Tbilisi - Gldani', type: 'district', parentCity: 'Tbilisi'})
CREATE (r8:Region {name: 'Tbilisi - Samgori', type: 'district', parentCity: 'Tbilisi'})
CREATE (r9:Region {name: 'Tbilisi - Nadzaladevi', type: 'district', parentCity: 'Tbilisi'})
CREATE (r10:Region {name: 'Tbilisi - Isani', type: 'district', parentCity: 'Tbilisi'})
CREATE (r11:Region {name: 'Tbilisi - Krtsanisi', type: 'district', parentCity: 'Tbilisi'})
CREATE (r12:Region {name: 'Tbilisi - Mtatsminda', type: 'district', parentCity: 'Tbilisi'})
CREATE (r13:Region {name: 'Tbilisi - Sololaki', type: 'district', parentCity: 'Tbilisi'})
CREATE (r14:Region {name: 'Tbilisi - Vera', type: 'district', parentCity: 'Tbilisi'})
CREATE (r15:Region {name: 'Tbilisi - Didube', type: 'district', parentCity: 'Tbilisi'})
CREATE (r16:Region {name: 'Tbilisi - Chugureti', type: 'district', parentCity: 'Tbilisi'})
CREATE (r17:Region {name: 'Tbilisi - Abanotubani', type: 'district', parentCity: 'Tbilisi'})
CREATE (r18:Region {name: 'Tbilisi - Vazisubani', type: 'district', parentCity: 'Tbilisi'})
CREATE (r19:Region {name: 'Batumi', type: 'city', country: 'Georgia'})
CREATE (r20:Region {name: 'Kutaisi', type: 'city', country: 'Georgia'})
CREATE (r21:Region {name: 'Rustavi', type: 'city', country: 'Georgia'})
CREATE (r22:Region {name: 'Gori', type: 'city', country: 'Georgia'})
CREATE (r23:Region {name: 'Zugdidi', type: 'city', country: 'Georgia'})
CREATE (r24:Region {name: 'Telavi', type: 'city', country: 'Georgia'})
CREATE (r25:Region {name: 'Akhmeta', type: 'city', country: 'Georgia'})
CREATE (r26:Region {name: 'Ozurgeti', type: 'city', country: 'Georgia'})
CREATE (r27:Region {name: 'Khashuri', type: 'city', country: 'Georgia'})
CREATE (r28:Region {name: 'Chiatura', type: 'city', country: 'Georgia'})
CREATE (r29:Region {name: 'Mtskheta', type: 'city', country: 'Georgia'})
CREATE (r30:Region {name: 'Martvili', type: 'city', country: 'Georgia'})
CREATE (r31:Region {name: 'Samtredia', type: 'city', country: 'Georgia'})
CREATE (r32:Region {name: 'Tedzami', type: 'city', country: 'Georgia'})
CREATE (r33:Region {name: 'Sagarejo', type: 'city', country: 'Georgia'})
CREATE (r34:Region {name: 'Sighnaghi', type: 'city', country: 'Georgia'})
CREATE (r35:Region {name: 'Kobuleti', type: 'city', country: 'Georgia'})
CREATE (r36:Region {name: 'Poti', type: 'city', country: 'Georgia'})
CREATE (r37:Region {name: 'Sukhumi', type: 'city', country: 'Georgia'})
CREATE (r38:Region {name: 'Other Regions', type: 'other', country: 'Georgia'})
CREATE (r39:Region {name: 'Unknown', type: 'unknown', country: 'Georgia'})
RETURN 'Created 39 Region nodes' as result;
